language: java

script: mvn verify

jdk:
 - openjdk7
 - oraclejdk8

cache:
  directories:
  - $HOME/.m2

notifications:
  email:
    recipients:
     - eg.oss@e-gineering.com

after_success:
  - mvn jacoco:report
  - mvn -N coveralls:report
